MOUSEKEY_ENABLE ?= no       # Mouse keys
CONSOLE_ENABLE ?= no        # Console for debug
COMMAND_ENABLE ?= no        # Commands for debug and configuration
NKRO_ENABLE ?= no           # USB Nkey Rollover
KEYMAP = n
include Makefile
